host: 0.0.0.0
mqtt_port: 1883
mqtt_ws_port: 8000
http_port: 8888

session_store_class: com.github.zjzcn.mqtt.store.MemorySessionStore

authenticator_class: com.github.zjzcn.mqtt.security.PermitAllAuthenticator
